[fish-eza]
src.git = "https://github.com/givensuman/fish-eza.git"
src.branch = "main"
fetch.github = "givensuman/fish-eza"

[fish-logo]
src.git = "https://github.com/laughedelic/fish_logo.git"
src.branch = "master"
fetch.github = "laughedelic/fish_logo"

[logseq-db]
src.cmd = '''curl -sH "User-Agent: nvfetcher" "https://api.github.com/repos/logseq/logseq/releases?per_page=100" | jq -r '[.[] | select([.assets[]?.name | select(endswith(".AppImage"))] | length > 0) | (.tag_name | split(".")[0] | try tonumber catch null) as $m | select($m != null and $m >= 2)][0].tag_name // empty' '''
fetch.url = "https://github.com/logseq/logseq/releases/download/$ver/Logseq-linux-x86_64-$ver.AppImage"

[logseq-md]
src.cmd = '''curl -sH "User-Agent: nvfetcher" "https://api.github.com/repos/logseq/logseq/releases?per_page=100" | jq -r '[.[] | select([.assets[]?.name | select(endswith(".AppImage"))] | length > 0) | (.tag_name | split(".")[0] | try tonumber catch null) as $m | select($m != null and $m < 2)][0].tag_name // empty' '''
fetch.url = "https://github.com/logseq/logseq/releases/download/$ver/Logseq-linux-x64-$ver.AppImage"

[betterbird-release]
src.httpheader = "https://www.betterbird.eu/downloads/get.php?os=linux&lang=en-US&version=release"
src.regex = 'betterbird-([0-9][^/]*)\.en-US\.linux-x86_64\.tar\.xz'
fetch.url = "https://www.betterbird.eu/downloads/LinuxArchive/betterbird-$ver.en-US.linux-x86_64.tar.xz"

[betterbird-future]
src.httpheader = "https://www.betterbird.eu/downloads/get.php?os=linux&lang=en-US&version=future"
src.regex = 'betterbird-([0-9][^/]*)\.en-US\.linux-x86_64\.tar\.xz'
fetch.url = "https://www.betterbird.eu/downloads/153-Preview/betterbird-$ver.en-US.linux-x86_64.tar.xz"
