# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  fish-eza = {
    pname = "fish-eza";
    version = "fb2d8c70e6d894d3b55259e4c4e659a4850581b0";
    src = fetchFromGitHub {
      owner = "givensuman";
      repo = "fish-eza";
      rev = "fb2d8c70e6d894d3b55259e4c4e659a4850581b0";
      fetchSubmodules = false;
      sha256 = "sha256-cFUHMSEMxq/XSeKOLCUArgM9ogY6NqrPmhxaHn5bbQs=";
    };
    date = "2026-02-06";
  };
  fish-logo = {
    pname = "fish-logo";
    version = "dc6a40836de8c24c62ad7c4365aa9f21292c3e6e";
    src = fetchFromGitHub {
      owner = "laughedelic";
      repo = "fish_logo";
      rev = "dc6a40836de8c24c62ad7c4365aa9f21292c3e6e";
      fetchSubmodules = false;
      sha256 = "sha256-DZXQt0fa5LdbJ4vPZFyJf5FWB46Dbk58adpHqbiUmyY=";
    };
    date = "2020-11-26";
  };
  logseq = {
    pname = "logseq";
    version = "2.0.1";
    src = fetchurl {
      url = "https://github.com/logseq/logseq/releases/download/2.0.1/Logseq-linux-x86_64-2.0.1.AppImage";
      sha256 = "sha256-Sd42cHizdnD+vbmH5WK3Xe4eGulsKL+4c4d5xCKX3Qw=";
    };
  };
}
